### ISSUE TITLE
update goreleaser.yaml to produce asset compliant release tarballs

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-slack-handler#4]
So Sensu Go Asset requires tarballs structured:
top-level:

  bin/   -> executables live in here
  lib/    -> required dynamic libraries
  include/ -> headers

It's a quick fix to the goreleaser yml.

**Comment by jspaleta** [comment]
actually the existing goreleaser.yml has a error in it. I'll do a pull request to fix it and do the binary file location change.

**Comment by nikkictl** [comment]
https://github.com/sensu/sensu-slack-handler/pull/5 made some big strides to get the packages closer to asset compliance. However after discussing with @jspaleta, we discovered goreleaser generates a non-configurable sha256 checksum (assets require sha512). Keeping this open to track that work.

**Comment by jspaleta** [comment]
I've updated the travis automation to push sha512 checksum as a post_deploy script in PR #8
